[workspace]
members = ["bin/host", "bin/input-gen", "crates/*"]
exclude = []
resolver = "2"

[workspace.package]
version = "0.4.0"
edition = "2021"

[workspace.dependencies]
revm = { version = "34.0.0", default-features = false }

# alloy
alloy-primitives = "1.5.4"
alloy = "1.6.0"
alloy-consensus = "1.6.0"
alloy-json-rpc = "1.6.0"
alloy-provider = "1.6.0"
alloy-rpc-client = "1.6.0"
alloy-transport = "1.6.0"
alloy-genesis = "1.6.0"
alloy-eips = "1.6.0"
alloy-rpc-types-eth = "1.6.0"

# reth
reth-stateless = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.2" }
reth-chainspec = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.2" }
reth-ethereum-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.2" }
reth-evm-ethereum = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.2" }
reth-rpc-api = { git = "https://github.com/paradigmxyz/reth", tag = "v1.10.2" }

# eth-act
stateless-validator-common = { git = "https://github.com/eth-act/ere-guests.git", rev = "885398bc1478e777096a8456bc925b2ab28a8d0f" } 
stateless-validator-reth = { git = "https://github.com/eth-act/ere-guests.git", rev = "885398bc1478e777096a8456bc925b2ab28a8d0f" }
witness-generator = { git = "https://github.com/eth-act/zkevm-benchmark-workload.git", rev = "8907be92536696319f04e6fdf40a07ebc93e891a" }
sparsestate = { git = "https://github.com/eth-act/zkvm-ethereum-mpt.git", rev = "a1e44638c49c4e16751a0b915593fce98ab6bdef" }

# common dependencies
anyhow = "1.0"
async-trait = "0.1"
bincode = "1.3.3"
clap = { version = "4.5.7", features = ["derive", "env"] }
dotenv = "0.15.0"
eyre = "0.6.12"
k256 = { version = "0.13.4" }
tiny-keccak = { version = "2.0.0", features = ["keccak"] }
rayon = "1.11.0"
serde = "1.0"
serde_with = "3.14"
serde_json = "1.0"
tokio = { version = "1.21", default-features = false, features = [
    "rt",
    "rt-multi-thread",
] }
tokio-util = { version = "0.7", features = ["rt"] }
url = "2.3"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
walkdir = "2"
jsonrpsee = { version = "0.26", features = ["http-client"] }
http = "1.4.0"
tempfile = "3"

