[package]
name = "input"
description = ""
version.workspace = true
edition.workspace = true

[dependencies]
guest-reth.workspace = true
guest-ethrex.workspace = true
zisk-sdk.workspace = true

ethrex-config.workspace = true
ethrex-common.workspace = true
ethrex-rpc.workspace = true

clap = { workspace = true, optional = true }
url = { workspace = true }

async-trait.workspace = true
anyhow.workspace = true
tracing.workspace = true

alloy-genesis.workspace = true
alloy-provider = { workspace = true, features = ["debug-api"] }
alloy-rpc-types-eth.workspace = true
alloy-rpc-types-debug.workspace = true

reth-chainspec.workspace = true

stateless-reth.workspace = true

[features]
cli = ["dep:clap"]
