[package]
name = "input"
description = ""
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
bincode.workspace = true
rayon.workspace = true
tracing.workspace = true
serde.workspace = true
serde_with.workspace = true

alloy-genesis.workspace = true
alloy-provider = { workspace = true, features = ["debug-api", "reqwest", "reqwest-rustls-tls"] }
alloy-rpc-types-debug.workspace = true

reth-chainspec.workspace = true
reth-ethereum-primitives.workspace = true

stateless.workspace = true

stateless-validator-reth = { workspace = true, features = ["host"] }
stateless-validator-common = { workspace = true, features = ["host"] }
