[package]
name = "zisk-eth-client"
description = ""
edition = "2021"
[workspace.package]

[dependencies]
bincode = "1.3.3"
rsp-client-executor = { git = "https://github.com/succinctlabs/rsp.git", rev = "24dee6c7bb4081f44e7d232fc924a9e419ee4c88" }
# rsp-client-executor = { path = "../../../rsp/crates/executor/client" }

ziskos = { git = "https://github.com/0xPolygonHermez/zisk.git" }
# Local development
# ziskos = { path = "../../../zisk/ziskos/entrypoint" }

[patch.crates-io]
# TODO: Add real URLs
# sha2 = { git = "https://github.com/0xPolygonHermez/zisk-patch-hashes.git", branch = "zisk-patch-sha2/v0.10.9" }
# sha3 = { git = "https://github.com/0xPolygonHermez/zisk-patch-hashes.git", branch = "zisk-patch-sha3/v0.10.8" }
# k256 = { git = "https://github.com/0xPolygonHermez/zisk-patch-elliptic-curves.git", branch = "zisk-patch-k256/v0.13.4" }
# sp1_bls12_381 = { git = "https://github.com/0xPolygonHermez/zisk-patch-bls12_381.git", branch = "zisk-patch/v0.8.0" }
# Local development
sha2 = { path = "../../../zisk-patch-sha2/sha2" }
sha3 = { path = "../../../zisk-patch-sha3/sha3" }
k256 = { path = "../../../zisk-patch-elliptic-curves/k256" }
sp1_bls12_381 = { path = "../../../zisk-patch-bls12_381" }
