[package]
name = "zisk-eth-client"
description = ""
edition = "2021"
[workspace.package]

[dependencies]
bincode = "1.3.3"
rsp-client-executor = { git = "https://github.com/succinctlabs/rsp.git", rev = "24dee6c7bb4081f44e7d232fc924a9e419ee4c88" }
# rsp-client-executor = { path = "../../../rsp/crates/executor/client" }
serde = "=1.0.219"

ziskos = { git = "https://github.com/0xPolygonHermez/zisk.git" }
# Local development
# ziskos = { path = "../../../../zisk/ziskos/entrypoint" }

[patch.crates-io]
sha2 = { git = "https://github.com/0xPolygonHermez/zisk-patch-hashes.git", tag = "patch-sha2-0.10.9-zisk-0.11.0" }
sha3 = { git = "https://github.com/0xPolygonHermez/zisk-patch-hashes.git", tag = "patch-sha3-0.10.8-zisk-0.11.0" }
k256 = { git = "https://github.com/0xPolygonHermez/zisk-patch-elliptic-curves.git", tag = "patch-k256-0.13.4-zisk-0.11.0" }
bn = { git = "https://github.com/0xPolygonHermez/zisk-patch-bn.git", tag = "patch-0.6.0-zisk-0.11.0", package = "substrate-bn" }
sp1_bls12_381 = { git = "https://github.com/0xPolygonHermez/zisk-patch-bls12_381.git", tag = "patch-0.8.0-zisk-0.11.0" }
# Local development
# sha2 = { path = "../../../zisk-patch-sha2/sha2" }
# sha3 = { path = "../../../zisk-patch-sha3/sha3" }
# k256 = { path = "../../../zisk-patch-elliptic-curves/k256" }
# bn = { path = "../../../zisk-patch-bn", package = "substrate-bn" }
# sp1_bls12_381 = { path = "../../../zisk-patch-bls12_381" }
