[package]
name = "guest-reth"
description = ""
version.workspace = true
edition.workspace = true

[dependencies]
alloy-primitives.workspace = true
alloy-genesis.workspace = true

reth-chainspec.workspace = true
reth-evm-ethereum.workspace = true

stateless-reth.workspace = true

zeth-mpt-state.workspace = true

stateless-validator-reth.workspace = true
