[package]
name = "guest-reth"
description = ""
version.workspace = true
edition.workspace = true

[dependencies]
k256.workspace = true
tiny-keccak.workspace = true

alloy-consensus = { workspace = true, features = ["crypto-backend"] }
alloy-primitives.workspace = true
alloy-genesis.workspace = true

revm.workspace = true

reth-chainspec.workspace = true
reth-evm-ethereum.workspace = true

stateless-reth.workspace = true

zeth-mpt-state.workspace = true

stateless-validator-reth.workspace = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_vendor, values("zisk"))', 'cfg(zisk_hints)', 'cfg(zisk_hints_debug)'] }
