[package]
name = "crypto"
description = "Custom cryptographic implementations for Zisk zkVM"
version.workspace = true
edition.workspace = true

[dependencies]
k256.workspace = true
tiny-keccak.workspace = true

revm.workspace = true

alloy-consensus = { workspace = true, default-features = false, features = ["crypto-backend", "k256"] }
alloy-primitives.workspace = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_vendor, values("zisk"))', 'cfg(zisk_hints)', 'cfg(zisk_hints_debug)'] }
