#[cfg(all(not(all(target_os = "zkvm", target_vendor = "zisk")), zisk_hints_debug))]
use std::os::raw::c_char;

// For the zkvm target: function declarations are generated by bindgen from
// zkvm_accelerators.h, ensuring they always exactly match the C standard header.
// If ziskos exports a function with an incompatible signature, this causes a
// compile-time type error at the call sites in impls.rs.
#[cfg(all(target_os = "zkvm", target_vendor = "zisk"))]
pub(crate) mod zkvm_api {
    #![allow(
        non_camel_case_types,
        non_snake_case,
        non_upper_case_globals,
        dead_code,
        clippy::all
    )]
    include!(concat!(env!("OUT_DIR"), "/zkvm_accelerators_bindings.rs"));
}

#[cfg(all(target_os = "zkvm", target_vendor = "zisk"))]
pub use zkvm_api::*;

#[cfg(all(not(all(target_os = "zkvm", target_vendor = "zisk")), zisk_hints))]
extern "C" {
    pub fn hint_sha256(f: *const u8, len: usize);

    pub fn hint_bn254_g1_add(p1: *const u8, p2: *const u8);

    pub fn hint_bn254_g1_mul(point: *const u8, scalar: *const u8);

    pub fn hint_bls12_381_g1_add(a: *const u8, b: *const u8);

    pub fn hint_bls12_381_g2_add(a: *const u8, b: *const u8);

    pub fn hint_secp256k1_ecrecover(sig: *const u8, recid: *const u8, msg: *const u8);

    pub fn hint_secp256k1_ecdsa_verify(sig: *const u8, msg: *const u8, pk: *const u8);

    pub fn hint_modexp_bytes(
        base_ptr: *const u8,
        base_len: usize,
        exp_ptr: *const u8,
        exp_len: usize,
        modulus_ptr: *const u8,
        modulus_len: usize,
    );

    pub fn hint_blake2b_compress(rounds: u32, h: *mut u64, m: *const u64, t: *const u64, f: u8);

    pub fn hint_secp256r1_ecdsa_verify(msg: *const u8, sig: *const u8, pk: *const u8);

    pub fn hint_verify_kzg_proof(
        z: *const u8,
        y: *const u8,
        commitment: *const u8,
        proof: *const u8,
    );

    pub fn hint_bn254_pairing_check(pairs: *const u8, num_pairs: usize);

    pub fn hint_bls12_381_g1_msm(pairs: *const u8, num_pairs: usize);

    pub fn hint_bls12_381_g2_msm(pairs: *const u8, num_pairs: usize);

    pub fn hint_bls12_381_pairing_check(pairs: *const u8, num_pairs: usize);

    pub fn hint_bls12_381_fp_to_g1(fp: *const u8);

    pub fn hint_bls12_381_fp2_to_g2(fp2: *const u8);

    pub fn pause_hints() -> bool;

    pub fn resume_hints();
}

#[cfg(all(not(all(target_os = "zkvm", target_vendor = "zisk")), zisk_hints_debug))]
extern "C" {
    pub fn hint_log_c(msg: *const c_char);
}
